@gatewayUrl = http://localhost:7000
@aggregatorUrl = http://localhost:7010
@notifierUrl = http://localhost:7020
@newsFeedUrl = http://localhost:7030
@quotesFeedUrl = http://localhost:7040
@weatherFeedUrl = http://localhost:7050

###
GET {{gatewayUrl}}

###
GET {{aggregatorUrl}}

###
GET {{notifierUrl}}

###
GET {{newsFeedUrl}}

###
GET {{quotesFeedUrl}}

###
GET {{weatherFeedUrl}}